### ISSUE TITLE
ReferenceError: verbose is not defined error

### ISSUE THREAD

**Issue by martinezjp** [xreader/git-for-humans#7]
Hello,
Thanks for this tool. It is very useful.
When doing "hgit show last commit" I get the following error:

> /usr/lib/node_modules/git-for-humans/commands/executor.js:32
>             if (verbose) {
>                 ^
> 
> ReferenceError: verbose is not defined
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/git-for-humans/commands/executor.js:32:17)
>     at emitTwo (events.js:111:20)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:920:16)
>     at Socket.<anonymous> (internal/child_process.js:351:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at Pipe._handle.close [as _onclose] (net.js:497:12)

Is there any work around for this error?

Thanks

JP Martinez

**Comment by xreader** [comment]
please pull last version, issue is fixed now
